# Generated by Django 4.1.7 on 2023-05-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_bookmark_alter_post_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시물', 'verbose_name_plural': '게시물'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='forum_post',
        ),
    ]
